### ISSUE TITLE
I want to see my tracking in a calendar view

### ISSUE THREAD

**Issue by linusyoung** [linusyoung/darka#3]
- [x] add detail view

- [x] hook list view to detail view

- [x] show summary of task
